files:
  include: 'styles/**/*.scss'
  exclude: 'styles/fontello/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 1
    - max-depth: 2
  border-zero:
    - 1
    - convention: 0
  brace-style:
    - 1
    - style: 1tbs
      allow-single-line: false
  class-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedbem
  clean-import-paths:
    - 1
    - leading-underscore: false
      filename-extension: false
  empty-args:
    - 1
    - include: true
  empty-line-between-blocks:
    - 1
    - include: true
  extends-before-declarations:
    - 1
  extends-before-mixins:
    - 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting:
    - 1
  force-element-nesting:
    - 1
  force-pseudo-nesting:
    - 1
  function-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations:
    - 1
    - exclude: []
  nesting-depth:
    - 1
    - max-depth: 4
  no-color-keywords:
    - 1
  no-color-literals:
    - 1
    - allow-rgba: false
  no-css-comments:
    - 1
  no-debug:
    - 1
  no-duplicate-properties:
    - 1
    - exclude: []
  no-empty-rulesets:
    - 1
  no-extends:
    - 0
  no-ids:
    - 1
  no-important:
    - 1
  no-invalid-hex:
    - 1
  no-mergeable-selectors:
    - 1
    - whitelist: []
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero:
    - 1
  no-transition-all:
    - 0
  no-url-protocols:
    - 1
  no-vendor-prefixes:
    - 1
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend:
    - 1
  placeholder-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - ignore-custom-properties: false
  property-units:
    - 1
    - global:
      - ch
      - em
      - ex
      - rem
      - cm
      - in
      - mm
      - pc
      - pt
      - px
      - q
      - vh
      - vw
      - vmin
      - vmax
      - deg
      - grad
      - rad
      - turn
      - ms
      - s
      - Hz
      - kHz
      - dpi
      - dpcm
      - dppx
      - '%'
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 1
    - allowed-shorthands: [1, 2, 3]
  single-line-per-selector:
    - 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-around-operator:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon:
    - 1
    - include: false
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon:
    - 1
    - include: true
  url-quotes:
    - 1
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit:
    - 1
    - include: false
