jobs:
  include:
    - stage: "Test"
      name: "Lint"
      language: node_js
      node_js: 8
      install:
        - npm install
        - npm install gulp-cli -g
      script:
        - gulp lint

notifications:
  email:
    on_success: never
    on_failure: change
