os: linux
dist: xenial
language: node_js

jobs:
  include:
    - stage: "Test"
      name: "Tests"
      language: node_js
      node_js: 10
      install:
        - npm install
        - npm install gulp-cli -g
      script:
        - gulp test
    - name: "Lint"
      language: node_js
      node_js: 10
      install:
        - npm install
        - npm install gulp-cli -g
      script:
        - gulp lint
    - name: "Accessibility"
      language: node_js
      node_js: 10
      addons:
        chrome: stable
      install:
        - npm install
        - npm install gulp-cli -g
      script:
        - gulp analyze:a11y
    - name: "Build dev"
      language: node_js
      node_js: 10
      install:
        - npm install
        - npm install gulp-cli -g
      script:
        - gulp build
    - name: "Build dist"
      language: node_js
      node_js: 10
      install:
        - npm install
        - npm install gulp-cli -g
      script:
        - gulp dist

    - stage: deploy
      name: "GitHub pages"
      language: node_js
      node_js: 10
      if: branch = master

      install:
        - npm install
        - npm install gulp-cli -g
      script:
        - gulp dist

      deploy:
        skip_cleanup: true
        local_dir: ./_site
        provider: pages
        token: $GITHUB_TOKEN
        strategy: git
        on:
          branch: master

notifications:
  email:
    on_success: never
    on_failure: change
