title: 'Eric Cornelissen'
keywords: 'eric,cornelissen'
lang: 'en-US'

collections:
  archive:
    collections_dir: 'archive'

exclude: ["guidelines/", "node_modules/", "fontello.json", "lighthouse-report.html", "package.json", "README.md"]

sass:
  sass_dir: styles
  style: compressed
fontello:
  config: 'fontello.json'
  fonts_path: '../assets/fonts'
  output_fonts: 'assets/fonts'
  output_styles: 'styles/fontello'
  preprocessor: 'scss'
